geekbrains/arhi_po/my_project/my_app/urls.py
from django.urls import path
from . import views


app_name = 'my_app'

urlpatterns = [
    path('', views.upload_transcription, name='upload_transcription'),
    path('word_timing/<int:pk>/', views.word_timing, name='word_timing'),
    path('download_audio/<int:transcription_id>/', views.download_audio, name='download_audio'),
    path('update_word_timing/<int:pk>/', views.update_word_timing, name='update_word_timing'),
    path('delete_word_timing/<int:pk>/', views.delete_word_timing, name='delete_word_timing'),
    path('export_txt/<int:transcription_id>/', views.export_txt, name='export_txt'),
    path('export_eaf/<int:transcription_id>/', views.export_eaf, name='export_eaf'),
]

geekbrains/arhi_po/my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('my_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekbrains/arhi_po/my_project/my_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Transcription(models.Model):
    text = models.TextField()
    audio_file = models.FileField(upload_to='audio_files/')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class WordTiming(models.Model):
    transcription = models.ForeignKey(Transcription, on_delete=models.CASCADE)
    start_time = models.FloatField()
    end_time = models.FloatField()
    word = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.word} ({self.start_time}-{self.end_time})"

geekbrains/arhi_po/my_project/my_app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Transcription, WordTiming

def validate_wav_file(value):
    if not value.name.endswith('.wav'):
        raise ValidationError("Файл должен быть в формате .wav")

def validate_txt_file(value):
    if not value.name.endswith('.txt'):
        raise ValidationError("Файл должен быть в формате .txt")

class TranscriptionForm(forms.ModelForm):
    class Meta:
        model = Transcription
        fields = ['text', 'audio_file', 'word_timing_file']
        labels = {
            'text': 'Текст',
            'audio_file': 'Аудиофайл',
            'word_timing_file': 'Файл тайминга слов (.txt)',
        }
    
    audio_file = forms.FileField(validators=[validate_wav_file])
    word_timing_file = forms.FileField(required=False, validators=[validate_txt_file])
    text = forms.CharField(widget=forms.Textarea, required=False)



class WordTimingForm(forms.ModelForm):
    class Meta:
        model = WordTiming
        fields = ('word', 'start_time', 'end_time', 'word_timing_file')
        labels = {
            'word': 'Слово',
            'start_time': 'Начало диапазона',
            'end_time': 'Конец диапазона',
            'word_timing_file': 'Файл тайминга слов (.txt)'
        }

    word_timing_file = forms.FileField(required=False, validators=[validate_txt_file])

geekbrains/arhi_po/my_project/my_app/views.py
# Импорт необходимых модулей Django и Python
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import FileResponse, JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.conf import settings

from .models import Transcription, WordTiming
from .forms import TranscriptionForm, WordTimingForm

import codecs
from pydub import AudioSegment
import json

# Функция для загрузки транскрипций
@login_required
def upload_transcription(request):
    if request.method == 'POST':
        form = TranscriptionForm(request.POST, request.FILES)
        if form.is_valid():
            transcription = form.save(commit=False)
            transcription.user = request.user
            transcription.save()

            # Обработка файла с таймингами слов, если он был загружен
            if request.FILES.get('word_timing_file'):
                word_timing_file = request.FILES['word_timing_file']
                word_timing_file.open(mode='rt')
                content = word_timing_file.read().decode('utf-8')
                for line in content.splitlines():
                    start_time, end_time, word = line.strip().split('\t')
                    WordTiming.objects.create(
                        transcription=transcription,
                        start_time=float(start_time),
                        end_time=float(end_time),
                        word=word
                    )
            else:
                # Если файл с таймингами слов не был загружен, генерируем их автоматически
                word_timings = generate_word_timings(transcription, transcription.audio_file)
                for start_time, end_time, word in word_timings:
                    WordTiming.objects.create(
                        transcription=transcription,
                        start_time=start_time,
                        end_time=end_time,
                        word=word
                    )

            return redirect('my_app:word_timing', pk=transcription.pk)
    else:
        form = TranscriptionForm()

    return render(request, 'my_app/upload_transcription.html', {'form': form})


# Функция для работы с таймингами слов
@login_required
def word_timing(request, pk):
    transcription = Transcription.objects.get(id=pk)
    if request.method == 'POST':
        form = WordTimingForm(request.POST, request.FILES)
        if form.is_valid():
            if request.FILES.get('word_timing_file'):
                word_timing_file = request.FILES['word_timing_file']
                word_timing_file.open(mode='rt')
                content = word_timing_file.read().decode('utf-8')
                for line in content.splitlines():
                    start_time, end_time, word = line.strip().split('\t')
                    WordTiming.objects.create(
                        transcription=transcription,
                        start_time=float(start_time),
                        end_time=float(end_time),
                        word=word
                    )
            else:
                word_timing = form.save(commit=False)
                word_timing.transcription = transcription
                word_timing.save()

            return redirect('my_app:word_timing', pk=transcription.id)
    else:
        form = WordTimingForm()
    word_timings = WordTiming.objects.filter(transcription=transcription)
    context = {
        'form': form,
        'word_timings': word_timings,
        'transcription_id': transcription.id,
        'audio_file_url': transcription.audio_file.url,  # Add this line
        'MEDIA_URL': settings.MEDIA_URL,
    }
    return render(request, 'my_app/word_timing.html', context)

def generate_word_timings(transcription, audio_file):
    audio = AudioSegment.from_file(audio_file.path)
    duration = audio.duration_seconds

    words = transcription.text.split()
    word_count = len(words)
    if word_count == 0:  # Если нет слов в тексте
        return []  # Вернуть пустой список

    time_per_word = duration / word_count

    word_timings = []
    padding_ratio = 0.1  # Определите отношение отступа к длительности аудио
    max_padding = 0.5  # Определите максимальный отступ между словами

    # Вычислите фактическую величину отступа на основе отношения отступа и ограничьте его максимальным значением
    padding = min(padding_ratio * time_per_word, max_padding)

    for i, word in enumerate(words):
        start_time = i * time_per_word + padding * i
        end_time = start_time + time_per_word
        word_timings.append((start_time, end_time, word))

    return word_timings


@login_required
def download_audio(request, transcription_id):
    transcription = Transcription.objects.get(id=transcription_id)
    return FileResponse(transcription.audio_file, as_attachment=True, filename=transcription.audio_file.name)

@login_required
def update_word_timing(request, pk):
    if request.method == 'POST':
        data = json.loads(request.body)
        start_time = float(data.get('start_time'))
        end_time = float(data.get('end_time'))
        word = data.get('word')

        word_timing = get_object_or_404(WordTiming, pk=pk)
        word_timing.start_time = start_time
        word_timing.end_time = end_time
        word_timing.word = word
        word_timing.save()

        return JsonResponse({"status": "success"})
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method"})





@csrf_exempt
@login_required
def delete_word_timing(request, pk):
    if request.method == 'POST':
        word_timing = get_object_or_404(WordTiming, pk=pk)
        word_timing.delete()
        return JsonResponse({"status": "success"})
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method"})

@login_required
def export_txt(request, transcription_id):
    transcription = get_object_or_404(Transcription, id=transcription_id)
    word_timings = WordTiming.objects.filter(transcription=transcription)

    response = HttpResponse(content_type='text/plain')
    response['Content-Disposition'] = f'attachment; filename="word_timings_{transcription_id}.txt"'

    for word_timing in word_timings:
        line = f"{word_timing.start_time}\t{word_timing.end_time}\t{word_timing.word}\n"
        response.write(line)

    return response

@csrf_exempt
@require_POST
def add_word_timing(request):
    if request.method == "POST":
        data = json.loads(request.body)
        transcription_id = data.get('transcription_id')
        start_time = data.get('start_time')
        end_time = data.get('end_time')
        word = data.get('word')
        transcription = get_object_or_404(Transcription, id=transcription_id)

        word_timing = WordTiming.objects.create(
            transcription=transcription,
            start_time=start_time,
            end_time=end_time,
            word=word
        )
        word_timing.save()
        return JsonResponse({'word_timing': {'id': word_timing.id, 'start_time': start_time, 'end_time': end_time}})
    else:
        return JsonResponse({'result': 'error', 'message': 'Неправильный метод запроса'})

def create_eaf_content(transcription):
    # Здесь должен быть код для создания содержимого EAF-файла
    # на основе данных транскрипции.
    # Возвращает строку с содержимым EAF-файла.

    # Для примера создадим пустой EAF-файл:
    eaf_content = '<?xml version="1.0" encoding="UTF-8"?>\n<ANNOTATION_DOCUMENT />'

    return eaf_content

def export_eaf(request, transcription_id):
    try:
        transcription = Transcription.objects.get(pk=transcription_id)
    except Transcription.DoesNotExist:
        # Обработка ошибки, если транскрипция не найдена
        return HttpResponse(status=404)

    # Создание содержимого EAF-файла на основе данных транскрипции
    eaf_content = create_eaf_content(transcription)

    # Установите имя файла в соответствии с вашими требованиями:
    file_name = f"transcription_{transcription_id}.eaf"

    response = HttpResponse(eaf_content, content_type='application/xml')
    response['Content-Disposition'] = f'attachment; filename={file_name}'
    return response

geekbrains/arhi_po/my_project/my_app/templates/my_app/upload_transcription.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h2>Загрузить транскрипцию</h2>
    <form method="post" enctype="multipart/form-data" class="form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Загрузить</button>
    </form>
    <p id="audioFileName"></p>
    <p id="wordTimingFileName"></p>
  </div>

  <script>
    document.getElementById('id_audio_file').addEventListener('change', function() {
      document.getElementById('audioFileName').textContent = "Audio file: " + this.files[0].name;
    });

    document.getElementById('id_word_timing_file').addEventListener('change', function() {
      document.getElementById('wordTimingFileName').textContent = "Word timing file: " + this.files[0].name;
    });
  </script>
{% endblock %}

geekbrains/arhi_po/my_project/my_app/templates/my_app/word_timing.html
{% extends "base.html" %}

{% block content %}
  <!-- Заголовок страницы -->
  <h1>Разметка Аудио</h1>


  <div id="waveform"></div>
  <div id="timeline"></div>


  <div id="word-timing-controls">
    <button id="play-btn">&#9658;</button>
    <button id="pause-btn">&#10074;&#10074;</button>
    <button id="stop-btn">&#9632;</button>    
  </div>

  <!-- Кнопки для сохранения, экспорта и управления масштабом -->
  <div>
    <button id="submit">Сохранить</button>
    <button id="export-btn" onclick="location.href='{% url 'my_app:export_txt' transcription_id %}'">Экспорт (TXT)</button>
    <!-- <button id="export-eaf-btn">Экспорт (EAF)</button> -->
    <label for="zoom-slider">Масштаб:</label>
    <input type="range" id="zoom-slider" min="1" max="100" value="1">
  </div>

  <!-- Форма для добавления нового слова -->
  <button id="toggle-add-form">Добавить</button>
  <div id="add-word-form" style="display: none;">
    <form id="add-word-form-element" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Добавить слово</button>
    </form>
  </div>

  <!-- Контейнер для отображения таймингов слов -->
  <div class="word-timings-container">
    <div class="word-timings">
      {% for word_timing in word_timings %}
      <div class="word-timing" data-id="{{ word_timing.id }}">
        <span>
          {{ word_timing.word }} ({{ word_timing.start_time|floatformat:2 }} - {{ word_timing.end_time|floatformat:2 }})
        </span>
        <button class="toggle-edit-btn">Редактировать</button>
        <button class="delete-btn" data-word-timing-id="{{ word_timing.id }}">Удалить</button>
        <!-- Форма для редактирования слова и его тайминга -->
        <div class="edit-controls" style="display: none;">
          <form class="edit-form" method="post" action="{% url 'my_app:update_word_timing' word_timing.id %}">
            {% csrf_token %}
            <label for="word">Слово:</label>
            <input type="text" name="word" id="word" value="{{ word_timing.word }}">
            <label for="start_time">Начало:</label>
            <input type="text" name="start_time" id="start_time" value="{{ word_timing.start_time|floatformat:2 }}">
            <label for="end_time">Конец:</label>
            <input type="text" name="end_time" id="end_time" value="{{ word_timing.end_time|floatformat:2 }}">
          </form>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <!-- Скрипты для работы аудиоплеера и обработки событий -->
  <script src="/static/js/wavesurfer.js"></script>
  <script src="/static/js/wavesurfer.timeline.min.js"></script>
  <script src="/static/js/wavesurfer.regions.min.js"></script>
  <script src="/static/js/wavesurfer.cursor.min.js"></script>
  <script src="/static/js/wavesurfer.spectrogram.js"></script>
  <script>
      document.addEventListener('DOMContentLoaded', () => {
          var wavesurfer = WaveSurfer.create({
              container: '#waveform',
              waveColor: 'violet',
              progressColor: 'purple',
              barWidth: 2,
              plugins: [
                  WaveSurfer.timeline.create({
                      container: '#timeline'
                  }),
                  WaveSurfer.regions.create(),
                  WaveSurfer.cursor.create({
                      showTime: true,
                      opacity: 1,
                      customShowTimeStyle: {
                          'background-color': '#000',
                          color: '#fff',
                          padding: '2px',
                          'font-size': '10px'
                      }
                  })
              ]
          });
          
          wavesurfer.load('{{ audio_file_url }}');
          document.getElementById('play-btn').addEventListener('click', () => {
              wavesurfer.play();
          });
          document.getElementById('pause-btn').addEventListener('click', () => {
              wavesurfer.pause();
          });
          document.getElementById('stop-btn').addEventListener('click', () => {
              wavesurfer.stop();
          });
          
          document.getElementById('toggle-add-form').addEventListener('click', () => {
              let addWordForm = document.getElementById('add-word-form');
              let toggleButton = document.getElementById('toggle-add-form');
              if (addWordForm.style.display === 'none') {
                  addWordForm.style.display = 'block';
                  toggleButton.textContent = 'Скрыть';
              } else {
                  addWordForm.style.display = 'none';
                  toggleButton.textContent = 'Добавить';
              }
          });
          document.querySelectorAll('.toggle-edit-btn').forEach((toggleButton, index) => {
              toggleButton.addEventListener('click', () => {
                  let wordTiming = toggleButton.closest('.word-timing');
                  let editControls = wordTiming.querySelector('.edit-controls');
                  if (editControls.style.display === 'none') {
                      editControls.style.display = 'block';
                      toggleButton.textContent = 'Скрыть';
                  } else {
                      editControls.style.display = 'none';
                      toggleButton.textContent = 'Редактировать';
                  }
              });
          });
          
          async function refreshPage() {
              const response = await fetch(window.location.href);
              const newDocument = new DOMParser().parseFromString(await response.text(), 'text/html');
              document.querySelector('.word-timings').innerHTML = newDocument.querySelector('.word-timings').innerHTML;
          }
          document.getElementById('submit').addEventListener('click', async () => {
              const forms = document.querySelectorAll('.edit-form');
              const promises = [];
              forms.forEach((editForm) => {
                  const url = editForm.getAttribute('action');
                  const word = editForm.querySelector('input[name="word"]').value;
                  const start_time = parseFloat(editForm.querySelector('input[name="start_time"]').value);
                  const end_time = parseFloat(editForm.querySelector('input[name="end_time"]').value);
                  const jsonBody = JSON.stringify({word, start_time, end_time});
                  const request = new Request(url, {
                      method: 'POST',
                      body: jsonBody,
                      headers: new Headers({
                          'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
                          'Content-Type': 'application/json'
                      })
                  });
                  promises.push(fetch(request));
              });
              try {
                  await Promise.all(promises);
                  alert('Изменения сохранены');
                  location.reload();
              } catch (error) {
                  console.error('Ошибка сохранения:', error);
                  alert('Произошла ошибка при сохранении изменений. Пожалуйста, попробуйте еще раз.');
              }
          });
          
          document.getElementById('add-word-form-element').addEventListener('submit', async (event) => {
              event.preventDefault();
              const formData = new FormData(event.target);
              const url = event.target.getAttribute('action') || window.location.href;
              try {
                  const response = await fetch(url, {
                      method: 'POST',
                      body: formData,
                      headers: new Headers({
                          'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
                      })
                  });
                  
                  if (response.ok) {
                      alert('Слово добавлено');
                      location.reload();
                  } else {
                      throw new Error(`Ошибка: ${response.statusText}`);
                  }
              } catch (error) {
                  console.error('Ошибка добавления слова:', error);
                  alert('Произошла ошибка при добавлении слова. Пожалуйста, попробуйте еще раз.');
              }
          });
          
          document.querySelector('#zoom-slider').oninput = function () {
              wavesurfer.zoom(Number(this.value));
          };
          document.querySelectorAll('.delete-btn').forEach((deleteBtn) => {
              deleteBtn.addEventListener('click', async (event) => {
                  event.preventDefault();
                  const wordTimingId = event.target.getAttribute('data-word-timing-id');
                  const deleteUrl = `{% url 'my_app:delete_word_timing' 0 %}`.replace('/0', `/${wordTimingId}`);
                  try {
                      const response = await fetch(deleteUrl, {
                          method: 'POST',
                          headers: new Headers({
                              'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
                          })
                      });
                      if (response.ok) {
                          alert('Слово удалено');
                          location.reload();
                      } else {
                          throw new Error(`Ошибка: ${response.statusText}`);
                      }
                  } catch (error) {
                      console.error('Ошибка удаления слова:', error);
                      alert('Произошла ошибка при удалении слова. Пожалуйста, попробуйте еще раз.');
                  }
              });
          });
          
          wavesurfer.on('ready', () => {
              {% for word_timing in word_timings %}
              wavesurfer.addRegion({
                  id: '{{ word_timing.id }}',
                  start: {{ word_timing.start_time }},
                  end: {{ word_timing.end_time }},
                  color: 'rgba(0, 255, 0, 0.3)'
              });
              {% endfor %}
          });
          
          wavesurfer.on('region-click', (region, e) => {
              wavesurfer.seekTo(region.start / wavesurfer.getDuration());
              let wordTiming = document.querySelector(`.word-timing[data-id="${region.id}"]`);
              let wordTimingText = wordTiming.querySelector('span');
              alert(`Selected word: ${wordTimingText.textContent}`);
          });
          
          wavesurfer.on('region-updated', (region) => {
              let wordTiming = document.querySelector(`.word-timing[data-id="${region.id}"]`);
              let startTimeInput = wordTiming.querySelector('#start_time');
              let endTimeInput = wordTiming.querySelector('#end_time');
              let wordTimingText = wordTiming.querySelector('span');
              
              startTimeInput.value = region.start.toFixed(2);
              endTimeInput.value = region.end.toFixed(2);
              
              let word = wordTiming.querySelector('#word').value;
              wordTimingText.textContent = `${word} (${region.start.toFixed(2)} - ${region.end.toFixed(2)})`;
          });
          
          // Экспорт в EAF-файл
          document.getElementById('export-eaf-btn').addEventListener('click', async () => {
              const exportUrl = '{% url "my_app:export_eaf" transcription_id %}';
              try {
                  const response = await fetch(exportUrl, {
                      method: 'GET',
                  });
                  
                  if (response.ok) {
                      const blob = await response.blob();
                      const url = window.URL.createObjectURL(blob);
                      const a = document.createElement('a');
                      a.href = url;
                      a.download = 'transcription.eaf';
                      a.click();
                      window.URL.revokeObjectURL(url);
                  } else {
                      throw new Error(`Ошибка: ${response.statusText}`);
                  }
              } catch (error) {
                  console.error('Ошибка экспорта в EAF:', error);
                  alert('Произошла ошибка при экспорте в EAF. Пожалуйста, попробуйте еще раз.');
              }
          });
      });
  </script>
{% endblock %}